feat: Implement overriding API methods and correct inconsistent naming
allan2/dotenvy pull request #47
Opened 2022-12-06 21:46 UTC by LeoniePhiline

This is a successor to https://github.com/allan2/dotenvy/pull/17 and the preferred alternative to https://github.com/allan2/dotenvy/pull/46.

# This PR

- Adds overriding variants to all relevant public API methods.
- Fixes documentation.
- Adds missing test for `from_read()`.
- Tests non-overriding behavior with greater precision.
- Tests overriding behavior correctly.
- Fixes some inconsistent test formatting.
- *Difference from #46:* Fixes inconsistent naming. See discussion in #46 for details.

2022-12-07 01:21 UTC, tshepang commented on dotenv/src/iter.rs
> +    /// into the environment.
```suggestion
    /// Loads all variables found in the `reader` into the environment, unless they already exist.
```
maybe this improves readability

2022-12-07 01:22 UTC, tshepang commented on dotenv/src/lib.rs
> +/// If you want the existing environment to take precendence,
```suggestion
/// If you want the existing environment to take precedence,
```

2022-12-07 09:37 UTC, sonro requested changes
Please remove `()` from function names in the documentation - for consistency with other Rust projects.

Example: `from_path_override()` becomes `from_path_override`.

2022-12-07 11:59 UTC, LeoniePhiline commented on dotenv/src/lib.rs
> +/// If you want the existing environment to take precendence,
Good catch, thank you!

2022-12-07 12:01 UTC, LeoniePhiline commented on dotenv/src/iter.rs
> +    /// into the environment.
Agreed, thanks!

2022-12-07 23:18 UTC, LeoniePhiline commented
@sonro PTAL

**Changes:** https://github.com/allan2/dotenvy/compare/392628a9610705d0948c0191ce520f2dc5189935..138476842bb73e423358e10943040461de94a1dd

2022-12-10 13:16 UTC, sonro approved these changes
Very good. Thank you for the changes.

2022-12-10 17:55 UTC, merged